#! /bin/sh
#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  - abdelmoneim
#  ╠╩╗╚═╗╠═╝║║║║║║  - 
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  - 

PATH="$HOME/.config/bspwm:$PATH"

#  ┬ ┬┌─┐┬─┐┬┌─┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐
#  ││││ │├┬┘├┴┐└─┐├─┘├─┤│  ├┤ └─┐
#  └┴┘└─┘┴└─┴ ┴└─┘┴  ┴ ┴└─┘└─┘└─┘

# workspaces() {
#	name=1
#	for monitor in $(bspc query -M); do
#		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
#		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
#		(( name++ ))
#	done
# }
#
# workspaces

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ┬  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬
#  │  ├─┤│ │││││  ├─┤  
#  ┴─┘┴ ┴└─┘┘└┘└─┘┴ ┴  

pgrep -x sxhkd > /dev/null || sxhkd &

#keyboard layout
setxkbmap -option grp:alt_shift_toggle us,ara &

#Polybar
killall -q polybar

while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

polybar mybar &


#redshift

killall -q redshift
while pgrep -u $UID -x redshift > /dev/null; do sleep 1; done
redshift &


#network manager

killall -q nm-applet
while pgrep -u $UID -x nm-applet > /dev/null; do sleep 1; done
nm-applet &

#dunst
killall -q dunst
while pgrep -u $UID -x dunst > /dev/null; do sleep 1; done
dunst &

killall -q mpd
while pgrep -u $UID -x mpd> /dev/null; do sleep 1; done
exec mpd &

#Gonme Authenticatio
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#tocuhpad
~/.config/bspwm/tap.sh &

#external sreen if found
~/.config/bspwm/externalscreen.sh &

#Picom
picom --config ~/.config/picom/picom.conf &


# Set system vars for polybar
. SetSysVars

#wallpaper
#feh -z --no-fehbg --bg-fill ~/Wallpaper
#nohup change_background.sh &
bash change_background.sh &

#  ┌┐ ┌─┐┌─┐┬ ┬┌┬┐  ┌─┐┌─┐┌┐┌┌─┐┬┌─┐
#  ├┴┐└─┐├─┘││││││  │  │ ││││├┤ ││ ┬
#  └─┘└─┘┴  └┴┘┴ ┴  └─┘└─┘┘└┘└  ┴└─┘
#         
bspc monitor eDP-1 -d "1:" "2:" "3:" "4:" "5:" "6:" "7:"
bspc monitor HDMI-1-0 -d 
#bspc monitor -d TERM WWW DEV FILE DOC 
#bspc monitor -d I II III IV V VI

bspc config border_width         1
#bspc config active_border_color #f7f23f
#bspc config normal_border_color #D23D3D


bspc config focused_border_color "#f7f23f"
#bspc config normal border color
#bspc config presel_feedback_color



bspc config window_gap          12
bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Microsoft-edge-dev desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a "Crow Translate" state=floating follow=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Cerebro focus=on state=floating follow=off
bspc rule -a Screenkey manage=off
bspc rule -a vlc desktop='^5'
bspc rule -a Nm-connection-editor state=floating follow=off

bspc config single_monocle                 true 
bspc config borderless_monocle            false
bspc config gapless_monocle               false

#bspc config focus_follows_pointer         true
#bspc config pointer_follows_focus         false
bspc config pointer_motion_interval       5
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

#cursor fix
xsetroot -cursor_name left_ptr
